DATA_SLICE: 'Spring' #Options ['General', 'Summer', 'Fall', 'Winter', 'Spring', 'Weekend', 'COVID Weekend', 'COVID']
PHASE: 'statistics' #Options ['train', 'predict', 'statistics']

PATHS:
  Data: './data/ForecastAnalyst_CalgaryDailyEnergyDataset_2023.xlsx'
  Model: './model/Summer.pkl'

TH: 0.4

